# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        /:year-:month-:day-:title/

# Setup
title:            Deversity
tagline:          Development Services
url:              http://www.deversity.co.uk
description:      ''
baseurl:          /

author:
  name:           Oliver Pearmain
  url:            http://www.oliverpearmain.com

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/Deversity/deversity.github.io
