# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Deversity
tagline:          Development Services
url:              http://www.deversity.uk
baseurl:          /
author:
  name:           Oliver Pearmain
  url:            http://www.oliverpearmain.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/Deversity/deversity.github.io
